{
    "name": "User",
    "type": "record",
    "fields": [
        {
            "name": "name",
            "type": "string"
        },
        {
            "name": "favorite_number",
            "type": "long"
        },
        {
            "name": "address",
            "type": {
                "name": "addressUnused",
                "type": "record",
                "fields": [
                    {"name":"street", "type":"string"}
                ]
            }
        },
        {
            "name": "favorite_color",
            "type": "string"
        }
    ]
}
