{
  "type": "record",
  "name": "RecommendationMessage",
  "namespace": "com.example",
  "fields": [
    {"name": "messageId", "type": "string"},
    {"name": "correlationId", "type": "string"},
    {"name": "causationId", "type": "string"},
    {"name": "schemaVersion", "type": "string"},
    {"name": "type", "type": "string"},
    {
      "name": "data",
      "type": {
        "type": "record",
        "name": "RecommendationData",
        "fields": [
          {"name": "DepartureDateTime", "type": "string"},
          {"name": "RouteLegCode", "type": "string"},
          {"name": "StartOfDayFreightPAX", "type": "int"},
          {"name": "MvsId", "type": "string"},
          {"name": "StartOfDayPassengerReservedLanemeters", "type": "int"},
          {"name": "StartOfDayPassengerRemainingLanemeters", "type": "int"},
          {"name": "StartOfDayFreightLanemeters", "type": "int"},
          {"name": "StartOfDayFreightFEU", "type": "int"},
          {"name": "StartOfDayPassengerReservedPAX", "type": "int"},
          {"name": "StartOfDayPassengerRemainingPAX", "type": "int"},
          {"name": "PredictedFreightLanemeters", "type": "float"},
          {"name": "PredictedFreightFEU", "type": "float"},
          {"name": "ProjectedFreightFEU", "type": "int"},
          {"name": "ProjectedFreightLanemeters", "type": "int"},
          {"name": "ProjectedFreightPAX", "type": "int"},
          {"name": "ProjectedPassengerHighDeckLanemeters", "type": "int"},
          {"name": "ProjectedPassengerPAX", "type": "int"},
          {"name": "RecommendedFreightFEU", "type": "int"},
          {"name": "RecommendedFreightLanemeters", "type": "int"},
          {"name": "RecommendedFreightPAX", "type": "int"},
          {"name": "RecommendedPassengerHighDeckLanemeters", "type": "int"},
          {"name": "RecommendedPassengerPAX", "type": "int"},
          {"name": "RecommendedLanemeterAction", "type": ["null", "string"], "default": null},
          {"name": "RecommendedPAXAction", "type": ["null", "string"], "default": null},
          {"name": "CreatedDateTimeUTC", "type": "string"}
        ]
      }
    }
  ]
}

