request_time_out = 1001

[kafka]
bootstrap_servers = "localhost:9092"
group_id = "this_config_file"
enable_auto_commit=false

[registry]
host = "http://localhost:8083/"

[connect]
host = "http://localhost:8083/"
