request_time_out = 1001
log_level = "INFO"
max_log_entries = 1000

[kafka]
bootstrap_servers = "localhost:9092"
group_id = "this_config_file"
enable_auto_commit=false

[registry]
host = "http://localhost:8081"

[connect]
host = "http://localhost:8083"
