name: Post coverage comment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write

jobs:
  post-comment:
    name: Post coverage comment
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download Pull Request comment
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: python-coverage-comment-action
          path: .

      - name: Post coverage comment
        uses: py-cov-action/python-coverage-comment-action@v4.1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          ACTIVITY: post_comment
